name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        # Artifact name
        name: Guessing Game # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ./target/release/Guessing-game-rs
        # The desired behavior if no files are found using the provided path.
        include-hidden-files: true
          
